ToDoListApp/Models/ToDoViewModel.cs
using ToDoListApp.Enums;

namespace ToDoListApp.Models
{
    public class ToDoViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public bool IsChecked { get; set; }
        public Priority Priority { get; set; }
        public ICollection<SubtaskViewModel> Subtasks { get; set; } = new List<SubtaskViewModel>();
    }
}

ToDoListApp/Controllers/SubtaskController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoListApp.Exceptions;
using ToDoListApp.Models;
using ToDoListApp.Services.Interfaces;

namespace ToDoListApp.Controllers
{
    public class SubtaskController : Controller
    {
        private readonly ISubtaskService _subtaskService;

        public SubtaskController(ISubtaskService subtaskService)
        {
            _subtaskService = subtaskService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int todoId, int listId)
        {
            try
            {
                var subtasks = await _subtaskService.GetSubtasksByTodoIdAsync(todoId);

                ViewData["TodoId"] = todoId;
                ViewData["ListId"] = listId;
                return View(subtasks);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveSubtasks(int todoId, int listId,List<SubtaskViewModel> tasks)
        {
            try
            {
                await _subtaskService.SaveSubtasksAsync(todoId, tasks);
                return RedirectToAction("Index", "ToDo", new { listId });
            }
            catch (ArgumentException)
            {
                return BadRequest();
            }
        }
    }
}

ToDoListApp/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoListApp.Exceptions;
using ToDoListApp.Models;
using ToDoListApp.Services;
using ToDoListApp.Services.Interfaces;

namespace ToDoListApp.Controllers
{
    public class ToDoController : Controller
    {
        private readonly IToDoService _toDoService;
        public ToDoController(IToDoService toDoService)
        {
            _toDoService = toDoService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int listId, string sortOrder = "default")
        {
            try
            {
                bool sortByPriority = sortOrder.Equals("priority");

                var viewModel = await _toDoService.GetTodosByListIdAsync(listId, sortByPriority);

                return View(viewModel);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        [HttpGet]
        public IActionResult Add(int listId)
        {
            var viewModel = new AddToDoViewModel();
            viewModel.ListId = listId;
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddToDoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await _toDoService.AddToDoAsync(model);
                return RedirectToAction("Index", new { listId = model.ListId });
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError("Name", ex.Message);
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Check(int todoId, int listId)
        {
            try
            {
                await _toDoService.MarkAsCheckedAsync(todoId);
                return RedirectToAction("Index", new { listId });
            }
            catch (InvalidOperationException ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index", new { listId });
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Uncheck(int todoId, int listId)
        {
            try
            {
                await _toDoService.MarkAsUncheckedAsync(todoId);
                return RedirectToAction("Index", new { listId });
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "An error occurred while unchecking the ToDo.";
                return RedirectToAction("Index", new { listId });
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var todo = await _toDoService.GetToDoByIdAsync(id);
                var model = new EditToDoViewModel
                {
                    Id = todo.Id,
                    Name = todo.Name,
                    DueDate = todo.DueDate,
                    Priority = todo.Priority,
                    ListId = todo.ListId
                };

                return View(model);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditToDoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await _toDoService.UpdateToDoAsync(model);
                return RedirectToAction("Index", new { listId = model.ListId });
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError("Name", ex.Message);
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var todo = await _toDoService.GetToDoByIdAsync(id);
                var model = new DeleteToDoViewModel
                {
                    Id = todo.Id,
                    Name = todo.Name,
                    ListId = todo.ListId
                };

                return View(model);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int listId)
        {
            try
            {
                await _toDoService.DeleteToDoAsync(id);
                return RedirectToAction("Index", new { listId } );
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }
    }
}

ToDoListApp/Views/ToDo/Add.cshtml
@using ToDoListApp.Enums
@model AddToDoViewModel

<h1>Add New ToDo</h1>

<form asp-action="Add" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="ListId" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="DueDate"></label>
        <input asp-for="DueDate" class="form-control" placeholder="YYYY-MM-DD" />
        <span asp-validation-for="DueDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Priority">Priority</label>
        <select asp-for="Priority" asp-items="@(Html.GetEnumSelectList<Priority>())" class="form-control"></select>
        <span asp-validation-for="Priority" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label for="TaskName">Task</label>
        <p id="TaskError" class="text-danger"></p>
        <input type="text" id="TaskName" class="form-control" />
        <button type="button" class="btn btn-primary mt-2" onclick="addTask()">Add Task</button>
        
    </div>

    <div id="TasksList" class="mt-3">
        <h5>Tasks:</h5>
        <ul id="TaskContainer"></ul>
    </div>

    <button type="submit" class="btn btn-success">Add</button>
    <a asp-action="Index" asp-route-ListId="@Model.ListId" class="btn btn-secondary">Cancel</a>
</form>


<script src="~/js/site.js"></script>

ToDoListApp/Views/ToDo/Delete.cshtml
@model DeleteToDoViewModel

<h1>Delete ToDo</h1>

<div class="alert alert-danger">
    Are you sure you want to delete the ToDo: <strong>@Model.Name</strong>?
</div>

<form asp-action="DeleteConfirmed" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="ListId" />
    <button type="submit" class="btn btn-danger">Delete</button>
    <a asp-action="Index" asp-route-listId="@Model.ListId" class="btn btn-secondary">Cancel</a>
</form>

ToDoListApp/Views/ToDo/Edit.cshtml
@using ToDoListApp.Enums
@model EditToDoViewModel

<h1>Edit ToDo</h1>

<form asp-action="Edit" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="ListId" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="DueDate"></label>
        <input asp-for="DueDate" class="form-control" placeholder="YYYY-MM-DD" />
        <span asp-validation-for="DueDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Priority">Priority</label>
        <select asp-for="Priority" asp-items="@(Html.GetEnumSelectList<Priority>())" class="form-control"></select>
        <span asp-validation-for="Priority" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-success">Save Changes</button>
    <a asp-action="Index" asp-route-listId="@Model.ListId" asp-route-sortOrder="default" class="btn btn-secondary">Cancel</a>
</form>

ToDoListApp/Views/ToDo/Index.cshtml
@model OpenListViewModel

<h1>@Model.ListName</h1>

<div class="text-center mb-3">
    <a asp-action="Index" asp-route-listId="@Model.ListId" asp-route-sortOrder="priority" class="btn btn-secondary">
        Sort by Priority
    </a>
</div>

@if (TempData["ErrorMessage"] != null)
{
        <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

<a asp-action="Add" asp-route-listId="@Model.ListId" class="btn btn-primary">Add ToDo</a>

<table class="table mt-4  todo-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Priority</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var todo in Model.Todos)
        {
            <tr>
                <td >
                    <span class="truncate-text @(todo.IsChecked ? "checked-item" : "")">@todo.Name</span>
                </td>
                <td>
                    @todo.Priority.ToString()
                </td>

                <td>
                    @if (todo.IsChecked)
                    {
                                <form asp-action="Uncheck" asp-route-todoId="@todo.Id" asp-route-listId="@Model.ListId"method="post" style="display:inline;">
                            <button type="submit" class="btn btn-success">Uncheck</button>
                        </form>
                    }
                    else
                    {
                       <form asp-action="Check" asp-route-todoId="@todo.Id" asp-route-listId="@Model.ListId" method="post" style="display:inline;">
                      <button type="submit" class="btn btn-primary">Check</button>
                      </form>
                        <a asp-action="Edit" asp-route-id="@todo.Id" class="btn btn-warning">Edit</a>
                        <form asp-action="Delete" asp-route-id="@todo.Id" method="get" style="display:inline;">
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                         <a asp-controller="Subtask" asp-action="Index" asp-route-todoId="@todo.Id" asp-route-listId="@Model.ListId" class="btn btn-info">Tasks</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>